-- return {
-- 	-- C# LSP
-- 	{
-- 		"seblyng/roslyn.nvim",
--     enabled = false,
-- 		ft = "cs",
-- 		opts = { -- defaults are fine if you'll install via Mason
-- 			-- leave empty unless you need custom `cmd` or `config`
-- 		},
-- 	},
-- }
return {}
